window.HISTORY_REGIONS = [
  { id: "europe",      name: "Europe",                 color: "#4f8dff" },
  { id: "middle-east", name: "Middle East & N. Africa", color: "#e8b94a" },
  { id: "south-asia",  name: "South Asia",             color: "#ff8a3d" },
  { id: "east-asia",   name: "East Asia",              color: "#ef4f5e" },
  { id: "africa",      name: "Sub-Saharan Africa",     color: "#3fbf75" },
  { id: "americas",    name: "Americas",               color: "#a463d6" },
  { id: "oceania",     name: "Oceania",                color: "#3ec0c0" }
];

window.HISTORY_EVENTS = [
  // ========================= EUROPE =========================
  { region: "europe", start: -776, end: -776, title: "First Olympic Games", type: "cultural", desc: "Pan-Hellenic athletic festival at Olympia." },
  { region: "europe", start: -753, end: -753, title: "Founding of Rome (legend)", type: "event", desc: "Romulus and Remus, traditional date." },
  { region: "europe", start: -509, end: -27, title: "Roman Republic", type: "period" },
  { region: "europe", start: -490, end: -490, title: "Battle of Marathon", type: "war", desc: "Athens defeats first Persian invasion." },
  { region: "europe", start: -480, end: -480, title: "Battle of Thermopylae & Salamis", type: "war", desc: "Greek city-states halt Persia." },
  { region: "europe", start: -431, end: -404, title: "Peloponnesian War", type: "war", desc: "Athens vs. Sparta." },
  { region: "europe", start: -336, end: -323, title: "Reign of Alexander the Great", type: "reign", desc: "Macedonian conquests reach India." },
  { region: "europe", start: -264, end: -146, title: "Punic Wars", type: "war", desc: "Rome vs. Carthage; Rome dominates Mediterranean." },
  { region: "europe", start: -49, end: -49, title: "Caesar crosses the Rubicon", type: "event" },
  { region: "europe", start: -27, end: 476, title: "Roman Empire (West)", type: "period" },
  { region: "europe", start: 79, end: 79, title: "Vesuvius destroys Pompeii", type: "event" },
  { region: "europe", start: 117, end: 117, title: "Roman Empire at greatest extent", type: "event", desc: "Under Trajan." },
  { region: "europe", start: 313, end: 313, title: "Edict of Milan", type: "religion", desc: "Christianity legalized in Rome." },
  { region: "europe", start: 410, end: 410, title: "Sack of Rome (Visigoths)", type: "war" },
  { region: "europe", start: 476, end: 476, title: "Fall of Western Roman Empire", type: "event" },
  { region: "europe", start: 527, end: 565, title: "Reign of Justinian (Byzantium)", type: "reign" },
  { region: "europe", start: 793, end: 1066, title: "Viking Age", type: "period" },
  { region: "europe", start: 800, end: 800, title: "Charlemagne crowned Emperor", type: "event" },
  { region: "europe", start: 1054, end: 1054, title: "Great Schism (E/W church split)", type: "religion" },
  { region: "europe", start: 1066, end: 1066, title: "Norman Conquest of England", type: "war" },
  { region: "europe", start: 1095, end: 1291, title: "Crusades", type: "war" },
  { region: "europe", start: 1215, end: 1215, title: "Magna Carta", type: "event" },
  { region: "europe", start: 1337, end: 1453, title: "Hundred Years' War", type: "war", desc: "England vs. France." },
  { region: "europe", start: 1347, end: 1351, title: "Black Death", type: "event", desc: "~30-50% of Europe's population dies." },
  { region: "europe", start: 1453, end: 1453, title: "Fall of Constantinople", type: "event" },
  { region: "europe", start: 1455, end: 1485, title: "Wars of the Roses", type: "war" },
  { region: "europe", start: 1492, end: 1492, title: "Columbus reaches the Americas", type: "event" },
  { region: "europe", start: 1517, end: 1517, title: "Luther's 95 Theses", type: "religion", desc: "Protestant Reformation begins." },
  { region: "europe", start: 1543, end: 1543, title: "Copernicus: heliocentric model", type: "discovery" },
  { region: "europe", start: 1558, end: 1603, title: "Reign of Elizabeth I", type: "reign" },
  { region: "europe", start: 1588, end: 1588, title: "Spanish Armada defeated", type: "war" },
  { region: "europe", start: 1618, end: 1648, title: "Thirty Years' War", type: "war" },
  { region: "europe", start: 1642, end: 1651, title: "English Civil War", type: "war" },
  { region: "europe", start: 1687, end: 1687, title: "Newton's Principia", type: "discovery" },
  { region: "europe", start: 1689, end: 1689, title: "Glorious Revolution", type: "event" },
  { region: "europe", start: 1701, end: 1714, title: "War of Spanish Succession", type: "war" },
  { region: "europe", start: 1756, end: 1763, title: "Seven Years' War", type: "war", desc: "First truly global war; theatres in Europe, Americas, India, Africa." },
  { region: "europe", start: 1789, end: 1799, title: "French Revolution", type: "event" },
  { region: "europe", start: 1803, end: 1815, title: "Napoleonic Wars", type: "war" },
  { region: "europe", start: 1815, end: 1815, title: "Battle of Waterloo", type: "war" },
  { region: "europe", start: 1848, end: 1848, title: "Revolutions of 1848", type: "event" },
  { region: "europe", start: 1853, end: 1856, title: "Crimean War", type: "war" },
  { region: "europe", start: 1859, end: 1859, title: "Darwin: On the Origin of Species", type: "discovery" },
  { region: "europe", start: 1861, end: 1861, title: "Italian Unification", type: "event" },
  { region: "europe", start: 1870, end: 1871, title: "Franco-Prussian War", type: "war" },
  { region: "europe", start: 1871, end: 1871, title: "German Unification", type: "event" },
  { region: "europe", start: 1914, end: 1918, title: "World War I", type: "war" },
  { region: "europe", start: 1917, end: 1917, title: "Russian Revolution", type: "event" },
  { region: "europe", start: 1936, end: 1939, title: "Spanish Civil War", type: "war" },
  { region: "europe", start: 1939, end: 1945, title: "World War II", type: "war" },
  { region: "europe", start: 1945, end: 1991, title: "Cold War", type: "period" },
  { region: "europe", start: 1957, end: 1957, title: "Treaty of Rome (EEC founded)", type: "event" },
  { region: "europe", start: 1989, end: 1989, title: "Fall of the Berlin Wall", type: "event" },
  { region: "europe", start: 1991, end: 1991, title: "Dissolution of the USSR", type: "event" },
  { region: "europe", start: 2022, end: 2022, title: "Russia invades Ukraine", type: "war" },

  // ========================= MIDDLE EAST & N. AFRICA =========================
  { region: "middle-east", start: -3100, end: -2686, title: "Early Dynastic Egypt", type: "period", desc: "Unification under Narmer." },
  { region: "middle-east", start: -2686, end: -2181, title: "Old Kingdom of Egypt", type: "period", desc: "Pyramid age." },
  { region: "middle-east", start: -2560, end: -2540, title: "Great Pyramid of Giza built", type: "cultural" },
  { region: "middle-east", start: -2334, end: -2154, title: "Akkadian Empire", type: "period", desc: "Sargon: first known empire." },
  { region: "middle-east", start: -2055, end: -1650, title: "Middle Kingdom of Egypt", type: "period" },
  { region: "middle-east", start: -1792, end: -1750, title: "Hammurabi reigns in Babylon", type: "reign", desc: "Famous law code." },
  { region: "middle-east", start: -1550, end: -1077, title: "New Kingdom of Egypt", type: "period" },
  { region: "middle-east", start: -1332, end: -1323, title: "Tutankhamun reigns", type: "reign" },
  { region: "middle-east", start: -1279, end: -1213, title: "Ramesses II reigns", type: "reign" },
  { region: "middle-east", start: -1200, end: -1150, title: "Bronze Age Collapse", type: "event", desc: "Civilizations across the Eastern Mediterranean fall." },
  { region: "middle-east", start: -911, end: -609, title: "Neo-Assyrian Empire", type: "period" },
  { region: "middle-east", start: -626, end: -539, title: "Neo-Babylonian Empire", type: "period" },
  { region: "middle-east", start: -550, end: -330, title: "Achaemenid Persian Empire", type: "period" },
  { region: "middle-east", start: -332, end: -332, title: "Alexander conquers Egypt & Persia", type: "war" },
  { region: "middle-east", start: -305, end: -30, title: "Ptolemaic Egypt", type: "period" },
  { region: "middle-east", start: -247, end: 224, title: "Parthian Empire", type: "period" },
  { region: "middle-east", start: -30, end: -30, title: "Death of Cleopatra; Egypt becomes Roman", type: "event" },
  { region: "middle-east", start: -4, end: 33, title: "Life of Jesus of Nazareth", type: "religion" },
  { region: "middle-east", start: 224, end: 651, title: "Sassanid Empire", type: "period" },
  { region: "middle-east", start: 570, end: 632, title: "Life of Muhammad", type: "religion" },
  { region: "middle-east", start: 622, end: 622, title: "Hijra: Islamic calendar begins", type: "religion" },
  { region: "middle-east", start: 661, end: 750, title: "Umayyad Caliphate", type: "period" },
  { region: "middle-east", start: 750, end: 1258, title: "Abbasid Caliphate", type: "period", desc: "Golden Age of Islam; Baghdad as cultural capital." },
  { region: "middle-east", start: 909, end: 1171, title: "Fatimid Caliphate", type: "period" },
  { region: "middle-east", start: 1037, end: 1194, title: "Seljuk Empire", type: "period" },
  { region: "middle-east", start: 1258, end: 1258, title: "Mongols sack Baghdad", type: "war", desc: "End of the Abbasid Caliphate." },
  { region: "middle-east", start: 1299, end: 1922, title: "Ottoman Empire", type: "period" },
  { region: "middle-east", start: 1453, end: 1453, title: "Ottoman conquest of Constantinople", type: "war" },
  { region: "middle-east", start: 1501, end: 1736, title: "Safavid Persia", type: "period" },
  { region: "middle-east", start: 1520, end: 1566, title: "Suleiman the Magnificent reigns", type: "reign" },
  { region: "middle-east", start: 1683, end: 1683, title: "Ottoman Siege of Vienna fails", type: "war" },
  { region: "middle-east", start: 1798, end: 1801, title: "Napoleon in Egypt", type: "war" },
  { region: "middle-east", start: 1869, end: 1869, title: "Suez Canal opens", type: "event" },
  { region: "middle-east", start: 1908, end: 1908, title: "Young Turk Revolution", type: "event" },
  { region: "middle-east", start: 1916, end: 1916, title: "Sykes-Picot Agreement", type: "event", desc: "Britain & France carve up the Middle East." },
  { region: "middle-east", start: 1948, end: 1948, title: "Founding of Israel", type: "event" },
  { region: "middle-east", start: 1979, end: 1979, title: "Iranian Revolution", type: "event" },
  { region: "middle-east", start: 1990, end: 1991, title: "Gulf War", type: "war" },
  { region: "middle-east", start: 2003, end: 2011, title: "Iraq War", type: "war" },
  { region: "middle-east", start: 2010, end: 2012, title: "Arab Spring", type: "event" },

  // ========================= SOUTH ASIA =========================
  { region: "south-asia", start: -2600, end: -1900, title: "Indus Valley Civilization", type: "period", desc: "Harappa, Mohenjo-daro." },
  { region: "south-asia", start: -1500, end: -500, title: "Vedic Period", type: "period", desc: "Composition of the Vedas." },
  { region: "south-asia", start: -563, end: -483, title: "Life of the Buddha (traditional)", type: "religion" },
  { region: "south-asia", start: -322, end: -185, title: "Maurya Empire", type: "period" },
  { region: "south-asia", start: -268, end: -232, title: "Reign of Ashoka", type: "reign", desc: "Buddhist conversion; pillars across India." },
  { region: "south-asia", start: 320, end: 550, title: "Gupta Empire (Golden Age)", type: "period", desc: "Mathematics, astronomy, classical Sanskrit literature." },
  { region: "south-asia", start: 711, end: 711, title: "Arab conquest of Sindh", type: "war" },
  { region: "south-asia", start: 1206, end: 1526, title: "Delhi Sultanate", type: "period" },
  { region: "south-asia", start: 1336, end: 1646, title: "Vijayanagara Empire", type: "period" },
  { region: "south-asia", start: 1469, end: 1539, title: "Guru Nanak (Sikhism)", type: "religion" },
  { region: "south-asia", start: 1526, end: 1857, title: "Mughal Empire", type: "period" },
  { region: "south-asia", start: 1556, end: 1605, title: "Reign of Akbar", type: "reign" },
  { region: "south-asia", start: 1632, end: 1653, title: "Taj Mahal built", type: "cultural" },
  { region: "south-asia", start: 1674, end: 1818, title: "Maratha Empire", type: "period" },
  { region: "south-asia", start: 1757, end: 1757, title: "Battle of Plassey", type: "war", desc: "British East India Company defeats Bengal; start of British India." },
  { region: "south-asia", start: 1857, end: 1858, title: "Indian Rebellion of 1857", type: "war" },
  { region: "south-asia", start: 1858, end: 1947, title: "British Raj", type: "period" },
  { region: "south-asia", start: 1930, end: 1930, title: "Salt March (Gandhi)", type: "event" },
  { region: "south-asia", start: 1947, end: 1947, title: "Indian Independence & Partition", type: "event" },
  { region: "south-asia", start: 1971, end: 1971, title: "Bangladesh Liberation War", type: "war" },

  // ========================= EAST ASIA =========================
  { region: "east-asia", start: -1600, end: -1046, title: "Shang Dynasty", type: "period" },
  { region: "east-asia", start: -1046, end: -256, title: "Zhou Dynasty", type: "period" },
  { region: "east-asia", start: -551, end: -479, title: "Confucius", type: "cultural" },
  { region: "east-asia", start: -475, end: -221, title: "Warring States Period", type: "period" },
  { region: "east-asia", start: -221, end: -206, title: "Qin Dynasty (1st unification)", type: "period", desc: "Qin Shi Huang; Great Wall begun." },
  { region: "east-asia", start: -206, end: 220, title: "Han Dynasty", type: "period", desc: "Silk Road, paper invented." },
  { region: "east-asia", start: 220, end: 280, title: "Three Kingdoms (China)", type: "period" },
  { region: "east-asia", start: 581, end: 618, title: "Sui Dynasty", type: "period" },
  { region: "east-asia", start: 618, end: 907, title: "Tang Dynasty (Golden Age)", type: "period" },
  { region: "east-asia", start: 794, end: 1185, title: "Heian Japan", type: "period", desc: "Tale of Genji; classical Japanese culture." },
  { region: "east-asia", start: 960, end: 1279, title: "Song Dynasty", type: "period", desc: "Gunpowder, movable type, paper money." },
  { region: "east-asia", start: 1185, end: 1333, title: "Kamakura Shogunate (Japan)", type: "period" },
  { region: "east-asia", start: 1206, end: 1368, title: "Mongol Empire / Yuan Dynasty", type: "period", desc: "Largest contiguous empire in history." },
  { region: "east-asia", start: 1271, end: 1295, title: "Marco Polo in Asia", type: "event" },
  { region: "east-asia", start: 1368, end: 1644, title: "Ming Dynasty", type: "period" },
  { region: "east-asia", start: 1405, end: 1433, title: "Zheng He's treasure voyages", type: "event" },
  { region: "east-asia", start: 1467, end: 1615, title: "Sengoku period (Japan)", type: "period", desc: "Civil war among daimyo." },
  { region: "east-asia", start: 1592, end: 1598, title: "Imjin War (Japan invades Korea)", type: "war" },
  { region: "east-asia", start: 1603, end: 1868, title: "Tokugawa Shogunate (Japan)", type: "period", desc: "Sakoku — Japan largely closed to foreigners." },
  { region: "east-asia", start: 1644, end: 1912, title: "Qing Dynasty", type: "period" },
  { region: "east-asia", start: 1735, end: 1796, title: "Reign of Qianlong Emperor", type: "reign", desc: "Qing dynasty at peak; Ten Great Campaigns." },
  { region: "east-asia", start: 1839, end: 1842, title: "First Opium War", type: "war" },
  { region: "east-asia", start: 1850, end: 1864, title: "Taiping Rebellion", type: "war", desc: "20-30 million deaths; one of history's deadliest conflicts." },
  { region: "east-asia", start: 1853, end: 1853, title: "Perry opens Japan", type: "event" },
  { region: "east-asia", start: 1868, end: 1868, title: "Meiji Restoration", type: "event", desc: "Japan modernizes rapidly." },
  { region: "east-asia", start: 1894, end: 1895, title: "First Sino-Japanese War", type: "war" },
  { region: "east-asia", start: 1904, end: 1905, title: "Russo-Japanese War", type: "war" },
  { region: "east-asia", start: 1911, end: 1912, title: "Xinhai Revolution — End of Qing", type: "event" },
  { region: "east-asia", start: 1937, end: 1945, title: "Second Sino-Japanese War", type: "war" },
  { region: "east-asia", start: 1949, end: 1949, title: "PRC founded under Mao", type: "event" },
  { region: "east-asia", start: 1950, end: 1953, title: "Korean War", type: "war" },
  { region: "east-asia", start: 1966, end: 1976, title: "Cultural Revolution", type: "event" },
  { region: "east-asia", start: 1989, end: 1989, title: "Tiananmen Square protests", type: "event" },

  // ========================= SUB-SAHARAN AFRICA =========================
  { region: "africa", start: -1000, end: 350, title: "Kingdom of Kush (Nubia)", type: "period" },
  { region: "africa", start: 100, end: 940, title: "Aksumite Empire", type: "period", desc: "Early Christian kingdom in modern Ethiopia." },
  { region: "africa", start: 700, end: 1240, title: "Ghana Empire", type: "period" },
  { region: "africa", start: 1000, end: 1500, title: "Great Zimbabwe", type: "period" },
  { region: "africa", start: 1235, end: 1670, title: "Mali Empire", type: "period" },
  { region: "africa", start: 1324, end: 1325, title: "Mansa Musa's Hajj", type: "event", desc: "Gold spending crashes Egyptian economy." },
  { region: "africa", start: 1464, end: 1591, title: "Songhai Empire", type: "period" },
  { region: "africa", start: 1500, end: 1900, title: "Atlantic Slave Trade", type: "period", desc: "~12 million Africans forcibly transported." },
  { region: "africa", start: 1652, end: 1652, title: "Dutch found Cape Town", type: "event" },
  { region: "africa", start: 1818, end: 1828, title: "Shaka Zulu / Mfecane", type: "war" },
  { region: "africa", start: 1881, end: 1914, title: "Scramble for Africa", type: "period", desc: "European colonial partition of the continent." },
  { region: "africa", start: 1899, end: 1902, title: "Second Boer War", type: "war" },
  { region: "africa", start: 1957, end: 1957, title: "Ghana — first independence", type: "event" },
  { region: "africa", start: 1960, end: 1960, title: "Year of Africa (17 indep.)", type: "event" },
  { region: "africa", start: 1967, end: 1970, title: "Nigerian Civil War (Biafra)", type: "war" },
  { region: "africa", start: 1994, end: 1994, title: "End of Apartheid (S. Africa)", type: "event" },
  { region: "africa", start: 1994, end: 1994, title: "Rwandan Genocide", type: "war" },

  // ========================= AMERICAS =========================
  { region: "americas", start: -1500, end: -400, title: "Olmec Civilization", type: "period", desc: "Mesoamerica's 'mother culture'." },
  { region: "americas", start: -200, end: 750, title: "Teotihuacan", type: "period" },
  { region: "americas", start: 250, end: 900, title: "Maya Classic Period", type: "period" },
  { region: "americas", start: 1100, end: 1532, title: "Inca Civilization", type: "period" },
  { region: "americas", start: 1325, end: 1521, title: "Aztec Empire", type: "period" },
  { region: "americas", start: 1492, end: 1492, title: "Columbus reaches the Americas", type: "event" },
  { region: "americas", start: 1519, end: 1521, title: "Spanish Conquest of Aztecs", type: "war" },
  { region: "americas", start: 1532, end: 1533, title: "Spanish Conquest of Inca", type: "war" },
  { region: "americas", start: 1607, end: 1607, title: "Jamestown founded", type: "event" },
  { region: "americas", start: 1620, end: 1620, title: "Mayflower lands", type: "event" },
  { region: "americas", start: 1754, end: 1763, title: "French and Indian War", type: "war", desc: "North American theatre of the Seven Years' War." },
  { region: "americas", start: 1775, end: 1783, title: "American Revolution", type: "war" },
  { region: "americas", start: 1787, end: 1787, title: "US Constitution", type: "event" },
  { region: "americas", start: 1791, end: 1804, title: "Haitian Revolution", type: "war", desc: "Only successful slave revolution; Haiti independent 1804." },
  { region: "americas", start: 1803, end: 1803, title: "Louisiana Purchase", type: "event" },
  { region: "americas", start: 1810, end: 1825, title: "Latin American Wars of Independence", type: "war" },
  { region: "americas", start: 1846, end: 1848, title: "Mexican-American War", type: "war" },
  { region: "americas", start: 1861, end: 1865, title: "US Civil War", type: "war" },
  { region: "americas", start: 1869, end: 1869, title: "Transcontinental Railroad completed", type: "event" },
  { region: "americas", start: 1898, end: 1898, title: "Spanish-American War", type: "war" },
  { region: "americas", start: 1910, end: 1920, title: "Mexican Revolution", type: "war" },
  { region: "americas", start: 1929, end: 1929, title: "Wall Street Crash", type: "event" },
  { region: "americas", start: 1959, end: 1959, title: "Cuban Revolution", type: "event" },
  { region: "americas", start: 1963, end: 1963, title: "JFK assassinated", type: "event" },
  { region: "americas", start: 1969, end: 1969, title: "Apollo 11 — Moon landing", type: "discovery" },
  { region: "americas", start: 2001, end: 2001, title: "September 11 attacks", type: "event" },

  // ========================= OCEANIA =========================
  { region: "oceania", start: -1000, end: 1300, title: "Polynesian Expansion", type: "period", desc: "Settlement of Pacific islands by canoe." },
  { region: "oceania", start: 1000, end: 1300, title: "Polynesians reach New Zealand", type: "event" },
  { region: "oceania", start: 1606, end: 1606, title: "Dutch reach Australia", type: "event" },
  { region: "oceania", start: 1768, end: 1779, title: "Cook's Pacific voyages", type: "event" },
  { region: "oceania", start: 1788, end: 1788, title: "First Fleet to Australia", type: "event" },
  { region: "oceania", start: 1840, end: 1840, title: "Treaty of Waitangi (NZ)", type: "event" },
  { region: "oceania", start: 1901, end: 1901, title: "Federation of Australia", type: "event" },
  { region: "oceania", start: 1942, end: 1942, title: "Battle of the Coral Sea", type: "war" },

  // ========================= ADDITIONS: Innovation, Religion, Culture =========================

  // ---- EUROPE ----
  { region: "europe", start: 380, end: 380, title: "Christianity becomes Roman state religion", type: "religion" },
  { region: "europe", start: 1184, end: 1184, title: "Medieval Inquisition established", type: "religion" },
  { region: "europe", start: 1304, end: 1374, title: "Petrarch (Renaissance humanism)", type: "cultural" },
  { region: "europe", start: 1378, end: 1417, title: "Western Schism (rival popes)", type: "religion" },
  { region: "europe", start: 1440, end: 1440, title: "Gutenberg's printing press", type: "discovery" },
  { region: "europe", start: 1452, end: 1519, title: "Leonardo da Vinci", type: "cultural" },
  { region: "europe", start: 1475, end: 1564, title: "Michelangelo", type: "cultural" },
  { region: "europe", start: 1564, end: 1616, title: "William Shakespeare", type: "cultural" },
  { region: "europe", start: 1609, end: 1609, title: "Galileo's telescope observations", type: "discovery" },
  { region: "europe", start: 1685, end: 1750, title: "J. S. Bach", type: "cultural" },
  { region: "europe", start: 1715, end: 1789, title: "The Enlightenment", type: "period" },
  { region: "europe", start: 1755, end: 1755, title: "Lisbon Earthquake", type: "event" },
  { region: "europe", start: 1756, end: 1791, title: "Mozart", type: "cultural" },
  { region: "europe", start: 1769, end: 1769, title: "Watt's improved steam engine", type: "discovery" },
  { region: "europe", start: 1770, end: 1827, title: "Beethoven", type: "cultural" },
  { region: "europe", start: 1796, end: 1796, title: "Smallpox vaccine (Jenner)", type: "discovery" },
  { region: "europe", start: 1804, end: 1804, title: "Steam locomotive (Trevithick)", type: "discovery" },
  { region: "europe", start: 1816, end: 1816, title: "Year Without a Summer (Tambora)", type: "event" },
  { region: "europe", start: 1837, end: 1837, title: "Electric telegraph", type: "discovery" },
  { region: "europe", start: 1869, end: 1869, title: "Periodic Table (Mendeleev)", type: "discovery" },
  { region: "europe", start: 1885, end: 1885, title: "First petrol automobile (Benz)", type: "discovery" },
  { region: "europe", start: 1895, end: 1895, title: "X-rays discovered (Röntgen)", type: "discovery" },
  { region: "europe", start: 1905, end: 1905, title: "Einstein's Special Relativity", type: "discovery" },
  { region: "europe", start: 1912, end: 1912, title: "Titanic sinks", type: "event" },
  { region: "europe", start: 1918, end: 1920, title: "Spanish Flu pandemic", type: "event" },
  { region: "europe", start: 1928, end: 1928, title: "Penicillin discovered (Fleming)", type: "discovery" },
  { region: "europe", start: 1953, end: 1953, title: "DNA structure described", type: "discovery" },
  { region: "europe", start: 1962, end: 1965, title: "Vatican II Council", type: "religion" },
  { region: "europe", start: 1986, end: 1986, title: "Chernobyl disaster", type: "event" },
  { region: "europe", start: 1989, end: 1989, title: "World Wide Web (Berners-Lee at CERN)", type: "discovery" },

  // ---- MIDDLE EAST ----
  { region: "middle-east", start: 70, end: 70, title: "Roman destruction of the Second Temple", type: "religion" },
  { region: "middle-east", start: 325, end: 325, title: "Council of Nicaea", type: "religion" },
  { region: "middle-east", start: 820, end: 820, title: "Al-Khwarizmi & the birth of algebra", type: "discovery" },
  { region: "middle-east", start: 1021, end: 1021, title: "Alhazen's Book of Optics", type: "discovery" },

  // ---- SOUTH ASIA ----
  { region: "south-asia", start: -599, end: -527, title: "Mahavira (Jainism)", type: "religion" },
  { region: "south-asia", start: 499, end: 499, title: "Aryabhata: zero, π, astronomy", type: "discovery" },

  // ---- EAST ASIA ----
  { region: "east-asia", start: 67, end: 67, title: "Buddhism arrives in China", type: "religion" },
  { region: "east-asia", start: 105, end: 105, title: "Paper invented (Cai Lun)", type: "discovery" },
  { region: "east-asia", start: 538, end: 538, title: "Buddhism arrives in Japan", type: "religion" },
  { region: "east-asia", start: 1010, end: 1010, title: "Tale of Genji (Murasaki Shikibu)", type: "cultural" },
  { region: "east-asia", start: 1041, end: 1048, title: "Movable type printing (Bi Sheng)", type: "discovery" },

  // ---- AFRICA ----
  { region: "africa", start: 350, end: 350, title: "Aksum converts to Christianity", type: "religion" },
  { region: "africa", start: 1804, end: 1903, title: "Sokoto Caliphate", type: "period" },
  { region: "africa", start: 1879, end: 1879, title: "Anglo-Zulu War", type: "war" },
  { region: "africa", start: 1884, end: 1885, title: "Berlin Conference (formalizes Scramble)", type: "event" },
  { region: "africa", start: 1948, end: 1948, title: "Apartheid established (S. Africa)", type: "event" },
  { region: "africa", start: 1963, end: 1963, title: "Organization of African Unity founded", type: "event" },
  { region: "africa", start: 2011, end: 2011, title: "South Sudan independence", type: "event" },

  // ---- AMERICAS ----
  { region: "americas", start: 1879, end: 1879, title: "Edison's incandescent light bulb", type: "discovery" },
  { region: "americas", start: 1903, end: 1903, title: "Wright Brothers' first flight", type: "discovery" },
  { region: "americas", start: 1906, end: 1906, title: "San Francisco earthquake", type: "event" },
  { region: "americas", start: 1947, end: 1947, title: "Transistor invented (Bell Labs)", type: "discovery" },
  { region: "americas", start: 1955, end: 1968, title: "US Civil Rights Movement", type: "event" },
  { region: "americas", start: 2007, end: 2007, title: "iPhone introduced", type: "discovery" },

  // ---- OCEANIA ----
  { region: "oceania", start: -1500, end: -500, title: "Lapita culture", type: "period" },
  { region: "oceania", start: 1521, end: 1521, title: "Magellan crosses the Pacific", type: "event" },
  { region: "oceania", start: 1642, end: 1642, title: "Tasman reaches NZ & Tasmania", type: "event" },
  { region: "oceania", start: 1845, end: 1872, title: "New Zealand Land Wars", type: "war" },
  { region: "oceania", start: 1907, end: 1907, title: "New Zealand becomes a Dominion", type: "event" },
  { region: "oceania", start: 1975, end: 1975, title: "Papua New Guinea independence", type: "event" },
  { region: "oceania", start: 1985, end: 1985, title: "Rainbow Warrior bombing", type: "event" }
];
